"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
format = """[â•” $username[@]($bone bolde)$hostname $fillâ•—](bold black)
[â• â• $directory$git_branch$git_status $fill$timeâ•â•](bold black)
[â•šâ•â• $status$character](bold black)"""

palette = 'rtissera'

[palettes.rtissera]
bone = '#ECE2D0'

[cmd_duration]
format = '[$duration]($style)'
show_milliseconds = true
min_time = 500

[fill]
symbol = 'â•'

[time]
disabled = false
format = ' ğŸ•™ [$time]($style) '
time_format = '%R'

[username]
format = '[$user]($style)'
show_always = true

[hostname]
ssh_only = false
format = '[$hostname]($style)'
 
[directory]
format = '[$path/]($style)'
truncation_symbol = '.../'

[git_branch]
format = '[-\[[$branch]($style)\]](bold $bone)'

[git_status]
format = '[($all_status$ahead_behind)]($style)'
ahead = 'ğŸš€'
behind = 'âª'
diverged = 'ğŸ”€'
renamed = 'âœï¸'
conflicted = 'ğŸ’¥'
up_to_date = '[âœ“](green)'
untracked = 'ğŸ¥¸'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](green)'
deleted = 'ğŸ—‘ï¸'

[character]
success_symbol = '[>](blue bold)'
error_symbol = '[>](red bold)'

[status]
format = '[\[$status\]]($style) '
map_symbol = true
disabled = false
